# Generated by Django 4.2.5 on 2023-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('userClass', models.PositiveIntegerField()),
                ('userType', models.CharField()),
                ('userName', models.CharField(max_length=15, unique=True)),
                ('realName', models.CharField()),
                ('userEmail', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('userCountry', models.CharField()),
                ('userFollwers', models.PositiveIntegerField()),
                ('userQualy', models.FloatField()),
                ('userDescr', models.CharField(max_length=150)),
            ],
        ),
    ]
