# Generated by Django 4.2.6 on 2023-10-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_delete_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userId',
            new_name='user',
        ),
    ]
