# Generated by Django 4.2.6 on 2023-10-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_userpic_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userPic',
            field=models.TextField(),
        ),
    ]
