# Generated by Django 4.2.5 on 2023-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTitle', models.TextField()),
                ('nBody', models.TextField()),
                ('nGeopos', models.PositiveIntegerField()),
            ],
        ),
    ]
