# Generated by Django 4.2.5 on 2023-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='nGeopos',
            field=models.TextField(),
        ),
    ]
