# Generated by Django 4.2.5 on 2023-11-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_news_ngeopos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='nGeopos',
        ),
    ]
