# Generated by Django 4.2.5 on 2023-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_news_lat_news_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='lat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='lng',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
