# Generated by Django 4.2.5 on 2023-11-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_news_lat_alter_news_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
        migrations.AddField(
            model_name='posts',
            name='lat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='lng',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='nBody',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='nTitle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
