# Generated by Django 4.2.5 on 2023-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_posts_nbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTitle', models.TextField()),
                ('nBody', models.TextField()),
                ('lat', models.IntegerField(default=0, null=True)),
                ('lng', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='nBody',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='nTitle',
        ),
    ]
