# Generated by Django 4.2.5 on 2023-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_delete_news_posts_lat_posts_lng_posts_nbody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='nImage',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
