# Generated by Django 4.2.5 on 2023-11-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_posts_nimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post',
        ),
    ]
