# Generated by Django 4.2.5 on 2023-11-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
